### ISSUE TITLE
Diocese bubbles not appearing in DP view

### ISSUE THREAD

**Issue by rwdorin** [corpus-synodalium/mapping#36]
I just noticed when running a search that numerous dioceses don't appear as bubbles in the DP viewer (look at England for clear examples) - any idea why this might be happening?
![Councils D](https://user-images.githubusercontent.com/37059795/101583759-feedc000-3990-11eb-96a4-264d0ccbe20a.jpg)
![Councils DP](https://user-images.githubusercontent.com/37059795/101583760-ff865680-3990-11eb-93c5-a79f93687f1d.jpg)
Here's the search that I ran that produced these:
https://cosyn.app/?url=https%3A%2F%2Fcorpus-synodalium.com%2Fphilologic%2Fcorpus%2Fquery%3Freport%3Dconcordance%26method%3Dproxy%26q%3Dconcil.*%2520lateran.*%2520%257C%2520general.*%26start%3D0%26end%3D0%26arg_proxy%3D5%26year%3D-1300

**Comment by thawsitt** [comment]
Hi Rowan, thanks for the example query. It's helpful!

I'll take a look when I have some bandwidth.

**Comment by thawsitt** [comment]
Fixed in this commit: https://github.com/corpus-synodalium/mapping/commit/5e09265b240a422c1db998e837e259ef75323f36
