### ISSUE TITLE
Update shapeFileID to jurisdictionID mappings (id_map.json)

### ISSUE THREAD

**Issue by thawsitt** [corpus-synodalium/mapping#9]
1. Currently, the code does not support one-to-many relationships. e.g. `"S0579": "D197/D106"`

2. Some shapeFileID values are empty. e.g. `"__2": "P088"`

Related file: [id_map.json](https://github.com/corpus-synodalium/mapping/blob/master/src/assets/id_map.json)

**Comment by thawsitt** [comment]
Note: The json has been updated with new mapping spreadsheet.

I think a shape file can only map to 1 diocese or province id. @rwdorin Can you confirm it that is correct?

Here is the latest json file we are using. It maps from "Shape File ID" => "Diocese ID"

https://github.com/corpus-synodalium/mapping/blob/dev/scripts/output/shapefile_data.json

**Comment by rwdorin** [comment]
Correct - each shapefile maps onto a single diocese or province.

**Comment by thawsitt** [comment]
Got it! I will close this issue then.
